# Tweets and Google+ posts
# tagged with '#cbio' will be 
# integrated into your profile.

Twitter:
Google+:


# The following three options specify
# a madlibs-style description of yourself.
# I ____________  at ____________________.
# I like ________________________________.
# No need for periods, we'll add them :)

I: write great code
at: the company I work for
I like: to do some extracurricular things for fun